# Generated by Django 3.0.6 on 2020-06-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
