# Generated by Django 3.0.6 on 2020-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=248)),
                ('quantity', models.IntegerField()),
                ('norm', models.IntegerField()),
                ('priority', models.NullBooleanField()),
                ('status', models.IntegerField(choices=[(0, 'not assigned'), (1, 'assigned'), (2, 'in progres'), (3, 'done'), (4, 'cancelled')], default=0)),
                ('placed_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
