# Generated by Django 3.0.6 on 2020-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana', '0009_auto_20200627_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
